=== bbeam/Hadoop/src/common/main/conf/cdcvalidation.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sourceDbName": {
      "type": "string"
    },
    "sourceTableName": {
      "type": "string"
    },
    "targetDbName": {
      "type": "string"
    },
    "targetTableName": {
      "type": "string"
    },
    "surrogateKey": {
      "type": "string"
    },
    "columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "isKeyColumn": {
            "type": "string"
          },
          "isNonKeyColumn": {
            "type": "string"
          },
          "isDateColumn": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "isKeyColumn",
          "isNonKeyColumn",
          "isDateColumn"
        ]
      }
    },
    "workDbName": {
      "type": "string"
    },
    "workTableName": {
      "type": "string"
    },
    "cdcPigFileForDim": {
      "type": "string"
    }
  },
  "required": [
    "sourceDbName",
    "sourceTableName",
    "targetDbName",
    "targetTableName",
    "surrogateKey",
    "columns",
    "workDbName",
    "workTableName",
    "cdcPigFileForDim"
  ]
}

=== bbeam/Hadoop/src/shareddim/main/conf/cdc_dim_members.json
{
     "sourceDbName":"WORK_SHARED_DIM_DB",
     "sourceTableName":"TF_TABLE_NAME",
     "targetDbName":"GOLD_SHARED_DIM_DB",
     "targetTableName":"TRGT_DIM_TABLE_NAME",
     "surrogateKey":"member_key",
     "columns":[
       {"name":"member_id","isKeyColumn":"true","isNonKeyColumn":"false","isDateColumn":"false"},
       {"name":"user_id","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"email","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"postal_code","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"pay_status","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"member_status","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"expiration_status","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"member_dt","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"true"},
       {"name":"membership_tier_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"primary_phone_number","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"first_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"last_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"associate","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"employee","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"market_key","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"}
     ], 
     "workDbName":"WORK_SHARED_DIM_DB",
     "workTableName":"WORK_DIM_TABLE_NAME",
     "cdcPigFileForDim":"dim_members"
}

=== bbeam/Hadoop/src/shareddim/main/conf/cdc_dim_service_provider.json
{
     "sourceDbName":"WORK_SHARED_DIM_DB",
     "sourceTableName":"TF_TABLE_NAME",
     "targetDbName":"GOLD_SHARED_DIM_DB",
     "targetTableName":"TRGT_DIM_TABLE_NAME",
     "surrogateKey":"service_provider_key",
     "columns":[
       {"name":"legacy_spid","isKeyColumn":"true","isNonKeyColumn":"false","isDateColumn":"false"},
       {"name":"new_world_spid","isKeyColumn":"true","isNonKeyColumn":"false","isDateColumn":"false"},
       {"name":"company_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"service_provider_group_type","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"entered_dt","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"true"},
       {"name":"city","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"state","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"postal_code","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"is_excluded","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"web_advertiser","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"call_center_advertiser","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"pub_advertiser","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"is_insured","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"is_bonded","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"is_licensed","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"background_check","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"ecommerce_status","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"vintage","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"market_key","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"}
     ], 
     "workDbName":"WORK_SHARED_DIM_DB",
     "workTableName":"WORK_DIM_TABLE_NAME",
     "cdcPigFileForDim":"dim_service_provider"
}

=== bbeam/Hadoop/src/shareddim/main/conf/cdc_dim_market.json
{
     "sourceDbName":"WORK_SHARED_DIM_DB",
     "sourceTableName":"TF_TABLE_NAME",
     "targetDbName":"GOLD_SHARED_DIM_DB",
     "targetTableName":"TRGT_DIM_TABLE_NAME",
     "surrogateKey":"market_key",
     "columns":[
       {"name":"market_id","isKeyColumn":"true","isNonKeyColumn":"false","isDateColumn":"false"},
       {"name":"market_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"}
     ], 
     "workDbName":"WORK_SHARED_DIM_DB",
     "workTableName":"WORK_DIM_TABLE_NAME",
     "cdcPigFileForDim":"dim_market"
}

=== bbeam/Hadoop/src/shareddim/main/conf/cdc_dim_category.json
{
     "sourceDbName":"WORK_SHARED_DIM_DB",
     "sourceTableName":"TF_TABLE_NAME",
     "targetDbName":"GOLD_SHARED_DIM_DB",
     "targetTableName":"TRGT_DIM_TABLE_NAME",
     "surrogateKey":"category_key",
     "columns":[
       {"name":"category_id","isKeyColumn":"true","isNonKeyColumn":"false","isDateColumn":"false"},
       {"name":"category","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"legacy_category","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"new_world_category","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"additional_category_nm","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"is_active","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"category_group","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"},
       {"name":"category_group_type","isKeyColumn":"false","isNonKeyColumn":"true","isDateColumn":"false"}
     ], 
     "workDbName":"WORK_SHARED_DIM_DB",
     "workTableName":"WORK_DIM_TABLE_NAME",
     "cdcPigFileForDim":"dim_category"
}
