=== bbeam/Hadoop/src/common/main/conf/dqvalidation.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "InputTableName": {
      "type": "string"
    },
    "OutputTableName": {
      "type": "string"
    },
    "SourceDB": {
      "type": "string"
    },
    "TargetDB": {
      "type": "string"
    },
    "DQHiveTableLocation": {
      "type": "string"
    },
    "TableValidation": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Check": {
            "type": "string"
          },
          "keyColumns": {
            "type": "string"
          },
          "Action": {
            "type": "string"
          }
        },
        "required": [
          "Check"
        ]
      }
    },
    "Columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string"
          },
          "Type": {
            "type": "string"
          },
          "Format": {
            "type": "string"
          },
          "Validations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Check": {
                  "type": "string"
                },
                "Action": {
                  "type": "string"
                },
                "Default": {
                  "type": "string"
                },
                "Values": {
                  "type": "string"
                }
              },
              "required": [
                "Check"
              ]
            }
          }
        },
        "required": [
          "Name",
          "Type",
          "Validations"
        ]
      }
    }
  },
  "required": [
    "InputTableName",
    "OutputTableName",
    "SourceDB",
    "TargetDB",
    "DQHiveTableLocation",
    "TableValidation",
    "Columns"
  ]
}

=== bbeam/Hadoop/src/legacy/main/conf/angie_dbo_dq_member_primary_address.json
{  
   "InputTableName":"inc_member_primary_address",
   "OutputTableName":"dq_member_primary_address",
   "SourceDB":"INCOMING_LEGACY_ANGIE_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angie/dbo/full/daily/dq_member_primary_address",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"member_primary_address_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"member_primary_address_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"member_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"member_address_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"known_invalid_postal_address",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"STRING",
         "Validations":[]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"STRING",
         "Validations":[]
      }	   
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_tbl_request_type_info.json
{  
   "InputTableName":"inc_tbl_request_type_info",
   "OutputTableName":"dq_tbl_request_type_info",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_tbl_request_type_info",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"request_info_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"bln_declined_alarm",
         "Type":"SMALLINT",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"cat_id",
         "Type":"INT",
         "Validations":[  
           
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"key_word",
         "Type":"STRING",
         "Validations":[  
           
         ]
      },
	  {  
         "Name":"request_count",
         "Type":"SMALLINT",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"request_id",
         "Type":"INT",
         "Validations":[  
           
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"request_info_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"request_type_id",
         "Type":"SMALLINT",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"sp_id",
         "Type":"INT",
         "Validations":[  
           
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
	
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_member_membership_tier.json
{  
   "InputTableName":"inc_member_membership_tier",
   "OutputTableName":"dq_member_membership_tier",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_member_membership_tier",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"member_membership_tier_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"member_membership_tier_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"member_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"membership_tier_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"original_purchase_price",
         "Type":"DECIMAL(10,2)",
         "Validations":[
         	{  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"STRING",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"STRING",
         "Validations":[]
      }	   
   ]
}

=== bbeam/Hadoop/src/alweb/main/conf/dq_t_service_provider.json
{  
   "InputTableName":"inc_t_service_provider",
   "OutputTableName":"dq_t_service_provider",
   "SourceDB":"ALWEB_INCOMING_DB",
   "TargetDB":"ALWEB_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_ALWEB/angieslist/full/daily/dq_service_provider",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"service_provider_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"service_provider_id",
         "Type":"INT",
          "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"listing_id",
         "Type":"INT",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"al_id",
		 "Type":"INT",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"name",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"hours",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"joined_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"description",
		 "Type":"STRING",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"services_offered",
		 "Type":"STRING",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"service_provider_type",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"in_business_since",
		 "Type":"INT",
         "Validations":[  
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  
	  {  
         "Name":"is_national",
		 "Type":"TINYINT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"status",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"version",
		 "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"create_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"create_by",
		 "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"update_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"update_by",
		 "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      }
	  
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/angie_dbo_dq_member_membership_tier.json
{  
   "InputTableName":"inc_member_membership_tier",
   "OutputTableName":"dq_member_membership_tier",
   "SourceDB":"INCOMING_LEGACY_ANGIE_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angie/dbo/full/daily/dq_member_membership_tier",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"member_membership_tier_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"member_membership_tier_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"member_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"membership_tier_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"original_purchase_price",
         "Type":"DECIMAL(10,2)",
         "Validations":[
         	{  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"STRING",
         "Validations":[  
            
         ]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"STRING",
         "Validations":[]
      },
      {  
         "Name":"green_thunder_membership_tier_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      } 
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_storefront_product_event.json
{  
   "InputTableName":"inc_storefront_product_event",
   "OutputTableName":"dq_storefront_product_event",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_storefront_product_event",
   "TableValidation":[  
      {  
         "Check":"Duplicate",
         "keyColumns":"storefront_product_event_id",
         "Action":"Reject"
      }
   ],
   "Columns":[  
      {  
         "Name":"campaign_id",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"create_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"create_date",
		 "Type":"TIMPESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"expiration_date",
		 "Type":"TIMPESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	    
      {  
         "Name":"member_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_item_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_product_event_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_product_event_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"update_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"update_date",
		 "Type":"TIMPESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      }
  ]
	  
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_service_provider_background_check.json
{  
   "InputTableName":"inc_service_provider_background_check",
   "OutputTableName":"dq_service_provider_background_check",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_service_provider_background_check",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"service_provider_background_check_id",
               "Action":"Reject"
            }
         ],
   "Columns":[
      {
         "Name":"service_provider_background_check_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"service_provider_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"first_name",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"last_name",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"profile_number",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"completed_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"background_check_status_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"create_by",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"update_by",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"update_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"customer_id",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
     ]
   }
