=== bbeam/Hadoop/src/common/main/conf/dqvalidation.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "InputTableName": {
      "type": "string"
    },
    "OutputTableName": {
      "type": "string"
    },
    "SourceDB": {
      "type": "string"
    },
    "TargetDB": {
      "type": "string"
    },
    "DQHiveTableLocation": {
      "type": "string"
    },
    "TableValidation": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Check": {
            "type": "string"
          },
          "keyColumns": {
            "type": "string"
          },
          "Action": {
            "type": "string"
          }
        },
        "required": [
          "Check"
        ]
      }
    },
    "Columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string"
          },
          "Type": {
            "type": "string"
          },
          "Format": {
            "type": "string"
          },
          "Validations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Check": {
                  "type": "string"
                },
                "Action": {
                  "type": "string"
                },
                "Default": {
                  "type": "string"
                },
                "Values": {
                  "type": "string"
                }
              },
              "required": [
                "Check"
              ]
            }
          }
        },
        "required": [
          "Name",
          "Type",
          "Validations"
        ]
      }
    }
  },
  "required": [
    "InputTableName",
    "OutputTableName",
    "SourceDB",
    "TargetDB",
    "DQHiveTableLocation",
    "TableValidation",
    "Columns"
  ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_markets.json
{  
   "InputTableName":"inc_markets",
   "OutputTableName":"dq_markets",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_markets",
   "TableValidation":[  
      {  
         "Check":"Duplicate",
         "keyColumns":"market_id",
         "Action":"Reject"
      }
   ],
   "Columns":[  
      {  
         "Name":"market_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
		{  
         "Name":"market",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"address1",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"address2",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"city",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"state",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"zip",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"phone1",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"phone2",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"fax",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"email",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"email2",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"email3",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"current_days",
		 "Type":"INT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"mm_first",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"mm_last",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"phone3",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"phone4",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"phone5",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"search_flag",
		 "Type":"SMALLINT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"bucket",
		 "Type":"INT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"int_detailed_sort",
		 "Type":"SMALLINT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"int_display_requirement",
		 "Type":"INT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"market_place_email",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"status",
		 "Type":"INT",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"fundraiser_phone",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"fundraiser_email",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"new_market_check",
		 "Type":"TINYINT",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            },
            {  
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }
            
         ]
      },
	  
	  {  
         "Name":"market_open_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"charter_end_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"alm",
         "Type":"TINYINT",
         "Validations":[
			{  
               "Check":"Null",
               "Action":"Reject"
            },		 
            {  
               "Check":"DataType",
               "Action":"Reject"
            },
            {  
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }
         ]
      },
	  
	  {  
         "Name":"toll_free_phone",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"toll_free_fax",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"default_radius",
		 "Type":"INT",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  
	  {  
         "Name":"country_code_id",
         "Type":"INT",
         "Validations":[
			{  
               "Check":"Null",
               "Action":"Reject"
            },		 
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  
      {  
         "Name":"market_url",
         "Type":"STRING",
         "Validations":[  
		   {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"big_deal",
		 "Type":"TINYINT",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            },
            {  
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }
            
         ]
      }
  ]
	  
}

=== bbeam/Hadoop/src/segment/main/conf/dq_greenpoint_production_search_the_list.json
{
   "InputTableName":"inc_greenpoint_production_search_the_list",
   "OutputTableName":"dq_greenpoint_production_search_the_list",   
   "SourceDB":"INCOMING_SEGMENT_EVENTS_GPP_DB",
   "TargetDB":"GOLD_SEGMENT_EVENTS_GPP_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/segment/events/greenpoint_production/incremental/daily/dq_greenpoint_production_search_the_list/edh_bus_date=$EDHBUSDATE",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {
         "Name":"id",
         "Type":"VARCHAR(254)",
         "Validations":[
		   {
               "Check":"Null",
               "Action":"Reject"
           },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"received_at",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"uuid",
         "Type":"BIGINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"anonymous_id",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_app_build",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_app_name",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_app_version",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_device_ad_tracking_enabled",
         "Type":"BOOLEAN",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            },
            {
            	"Check":"ValuesConstraint",
	            "Values":"true,false"
            }
         ]
      },
      {
         "Name":"context_device_idfa",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_device_idfv",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_device_manufacturer",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_device_model",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_device_type",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_ip",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_library_name",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_library_version",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_locale",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_network_bluetooth",
         "Type":"BOOLEAN",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            },
            {
            	"Check":"ValuesConstraint",
	            "Values":"true,false"
            }			
         ]
      },
      {
         "Name":"context_network_carrier",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_network_wifi",
         "Type":"BOOLEAN",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            },
			{
            	"Check":"ValuesConstraint",
	            "Values":"true,false"
            }
         ]
      },
      {
         "Name":"context_os_name",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_os_version",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_screen_height",
         "Type":"BIGINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"context_screen_width",
         "Type":"BIGINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"event",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"event_text",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"original_timestamp",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"sent_at",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"sp_category",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"sp_keyword",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"timestamp",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"user_id",
         "Type":"VARCHAR(256)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"member_id_legacy",
         "Type":"BIGINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"user_id40",
         "Type":"BIGINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"uuid_ts",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
 		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",		 
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
  ]
}

=== bbeam/Hadoop/src/alweb/main/conf/angieslist_dq_t_invoice_item.json
{  
   "InputTableName":"inc_t_invoice_item",
   "OutputTableName":"dq_t_invoice_item",
   "SourceDB":"INCOMING_ALWEB_AL_DB",
   "TargetDB":"GOLD_ALWEB_AL_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/alweb/angieslist/full/daily/dq_t_invoice_item",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"invoice_item_id",
               "Action":"Reject"
            }
         ],
   "Columns":[
   {
         "Name":"invoice_item_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"invoice_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"sku_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"item_type",
         "Type":"VARCHAR(254)",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"kind",
         "Type":"VARCHAR(254)",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"price",
         "Type":"DECIMAL(10,2)",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"quantity",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"description",
         "Type":"String",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"prepaid_job_sku_item_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"coupon_code",
         "Type":"VARCHAR(45)",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {
         "Name":"version",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },      
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
    ]
}

=== bbeam/Hadoop/src/alweb/main/conf/dq_t_category.json
{  
   "InputTableName":"inc_t_category",
   "OutputTableName":"dq_t_category",
   "SourceDB":"INCOMING_ALWEB_AL_DB",
   "TargetDB":"GOLD_ALWEB_AL_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/alweb/angieslist/full/daily/dq_t_category",
   "TableValidation":[  
      {  
         "Check":"Duplicate",
         "keyColumns":"category_id",
         "Action":"Reject"
      }
   ],
   "Columns":[  
      {  
         "Name":"category_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
		{  
         "Name":"name",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
      {  
         "Name":"status",
		 "Type":"varchar(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss.SSS",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
     ]
}
