=== bbeam/Hadoop/src/common/main/conf/dqvalidation.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "InputTableName": {
      "type": "string"
    },
    "OutputTableName": {
      "type": "string"
    },
    "SourceDB": {
      "type": "string"
    },
    "TargetDB": {
      "type": "string"
    },
    "DQHiveTableLocation": {
      "type": "string"
    },
    "TableValidation": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Check": {
            "type": "string"
          },
          "keyColumns": {
            "type": "string"
          },
          "Action": {
            "type": "string"
          }
        },
        "required": [
          "Check"
        ]
      }
    },
    "Columns": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string"
          },
          "Type": {
            "type": "string"
          },
          "Format": {
            "type": "string"
          },
          "Validations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Check": {
                  "type": "string"
                },
                "Action": {
                  "type": "string"
                },
                "Default": {
                  "type": "string"
                },
                "Values": {
                  "type": "string"
                }
              },
              "required": [
                "Check"
              ]
            }
          }
        },
        "required": [
          "Name",
          "Type",
          "Validations"
        ]
      }
    }
  },
  "required": [
    "InputTableName",
    "OutputTableName",
    "SourceDB",
    "TargetDB",
    "DQHiveTableLocation",
    "TableValidation",
    "Columns"
  ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_service_provider.json
{  
   "InputTableName":"inc_service_provider",
   "OutputTableName":"dq_service_provider",
   "SourceDB":"INCOMING_LEGACY_ANGIE_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angie/dbo/full/daily/dq_service_provider",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"sp_id",
               "Action":"Reject"
            }
         ],
   "Columns":[
      {
         "Name":"sp_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"sp_status_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"company_name",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"entered_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST", 		 
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"address_1",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"address_2",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"city",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"state",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"zip",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"business_date",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"contact_title",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"contact_first",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"contact_middle",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"contact_last",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"phone",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"phone_2",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"voice_star_number",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"fax",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"email",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"url",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"senior_discount",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"non_services",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"services",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"operating_hours",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"service_area",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"bus_desc",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"bbb",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"exclude_reason",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"internal_comment",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"emergency_service",
         "Type":"TINYINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            },
            {
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }
         ]
      },
       {
         "Name":"create_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "Format":"yyyy-MM-dd HH:mm:ss",
		 "TimeZone":"UTC",		 
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"create_by",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"country_code_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"legal_business_name",
         "Type":"STRING",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"classic_import_work_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"known_invalid_email_address",
         "Type":"TINYINT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            },
            {
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }
         ]
      },
       {
         "Name":"postal_address_status_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"phone_status_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
    ]
}

=== bbeam/Hadoop/src/legacy/main/conf/angie_dbo_dq_service_provider_group_association.json
{  
   "InputTableName":"inc_service_provider_group_association",
   "OutputTableName":"dq_service_provider_group_association",
   "SourceDB":"INCOMING_LEGACY_ANGIE_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angie/dbo/full/daily/dq_service_provider_group_association",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"service_provider_group_association_id",
               "Action":"Reject"
            }
         ],
   "Columns":[
   {
         "Name":"service_provider_group_association_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"service_provider_group_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"sp_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
    ]
}

=== bbeam/Hadoop/src/legacy/main/conf/angieanalytics_dbo_dq_storefront_product_event.json
{  
   "InputTableName":"inc_storefront_product_event",
   "OutputTableName":"dq_storefront_product_event",
   "SourceDB":"INCOMING_LEGACY_ANGIE_ANALYTICS_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_ANALYTICS_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angieanalytics/dbo/incremental/daily/dq_storefront_product_event/edh_bus_date=$EDH_BUS_DATE",
   "TableValidation":[  
      {  
         "Check":"Duplicate",
         "keyColumns":"storefront_product_event_id",
         "Action":"Reject"
      }
   ],
   "Columns":[  
      {  
         "Name":"storefront_product_event_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_item_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"member_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_product_event_type_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	   {  
         "Name":"expiration_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },	  
	  {  
         "Name":"campaign_id",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"create_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	 
	  {  
         "Name":"create_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
		{  
         "Name":"update_date",
		 "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
           {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },	  
	  {  
         "Name":"update_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      }
	  
  ]
	  
}

=== bbeam/Hadoop/src/alweb/main/conf/angieslist_dq_t_associate_permission.json
{  
   "InputTableName":"inc_t_associate_permission",
   "OutputTableName":"dq_t_associate_permission",
   "SourceDB":"INCOMING_ALWEB_AL_DB",
   "TargetDB":"GOLD_ALWEB_AL_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/alweb/angieslist/full/daily/dq_t_associate_permission",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"associate_permission_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"associate_permission_id ",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"  al_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"user_id",
         "Type":"INT",
         "Validations":[
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"service_provider_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"name",
         "Type":"VARCHAR(254)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            }			
         ]
      },
      {  
         "Name":"value",
         "Type":"TINYINT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            },
            {  
               "Check":"ValuesConstraint",
               "Values":"0,1"
            }			
         ]
      },	   
      {  
         "Name":"version",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },      
      {  
         "Name":"create_date",
         "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"create_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_date",
         "Type":"TIMESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSS",
		 "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"update_by",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_storefront_product_event_type.json
{  
   "InputTableName":"inc_storefront_product_event_type",
   "OutputTableName":"dq_storefront_product_event_type",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_storefront_product_event_type",
   "TableValidation":[  
      {  
         "Check":"Duplicate",
         "keyColumns":"storefront_product_event_type_id",
         "Action":"Reject"
      }
   ],
   "Columns":[  
      {  
         "Name":"create_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"create_date",
		 "Type":"TIMPESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"storefront_product_event_type_description",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"storefront_product_event_type_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
	  {  
         "Name":"storefront_product_event_type_name",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"Null",
               "Action":"Reject"
            },
			{  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	   {  
         "Name":"update_by",
		 "Type":"STRING",
         "Validations":[  
             {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      },
	  {  
         "Name":"update_date",
		 "Type":"TIMPESTAMP",
		 "Format":"yyyy-MM-dd HH:mm:ss.SSSSSS",
         "Validations":[  
           {  
               "Check":"DataType",
               "Action":"Reject"
            }
            
         ]
      }
  ]
	  
}

=== bbeam/Hadoop/src/legacy/main/conf/angie_dbo_dq_postal_address.json
{  
   "InputTableName":"inc_postal_address",
   "OutputTableName":"dq_postal_address",
   "SourceDB":"INCOMING_LEGACY_ANGIE_DBO_DB",
   "TargetDB":"GOLD_LEGACY_ANGIE_DBO_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/legacy/angie/dbo/full/daily/dq_postal_address",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"postal_address_id",
               "Action":"Reject"
            }
         ],
   "Columns":[  
      {  
         "Name":"postal_address_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"postal_format_id",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"address1",
         "Type":"STRING",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"address2",
         "Type":"STRING",
         "Validations":[
            
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
       {  
         "Name":"city",
         "Type":"STRING",
         "Validations":[
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
       {  
         "Name":"state",
         "Type":"STRING",
         "Validations":[
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
       {  
         "Name":"postal_code",
         "Type":"STRING",
         "Validations":[
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
       {  
         "Name":"country_code_id",
         "Type":"INT",
         "Validations":[
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
       },
      {  
         "Name":"latitude",
         "Type":"DECIMAL(19,9)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"longitude",
         "Type":"DECIMAL(19,9)",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"coordinate_confidence",
         "Type":"INT",
         "Validations":[  
            {  
               "Check":"Null",
               "Action":"Reject"
            },
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
      {  
         "Name":"process_date",
         "Type":"TIMESTAMP",
         "Format":"yyyy-MM-dd HH:mm:ss",
         "TimeZone":"UTC",
		 "ConvertToTimeZone":"EST",
         "Validations":[  
            {  
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
   ]
}

=== bbeam/Hadoop/src/legacy/main/conf/dq_service_provider_group_association.json
{  
   "InputTableName":"inc_service_provider_group_association",
   "OutputTableName":"dq_service_provider_group_association",
   "SourceDB":"LEGACY_INCOMING_DB",
   "TargetDB":"LEGACY_GOLD_DB",
   "DQHiveTableLocation":"$S3_BUCKET/data/gold/$SOURCE_LEGACY/angie/full/daily/dq_service_provider_group_association",
   "TableValidation":[  
            {  
               "Check":"Duplicate",
               "keyColumns":"service_provider_group_association_id",
               "Action":"Reject"
            }
         ],
   "Columns":[
   {
         "Name":"service_provider_group_association_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"service_provider_group_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      },
       {
         "Name":"sp_id",
         "Type":"INT",
         "Validations":[
            {
               "Check":"Null",
               "Action":"Reject"
            },
            {
               "Check":"DataType",
               "Action":"Reject"
            }
         ]
      }
    ]
}
